server:
  address: 0.0.0.0

spring:
  cloud:
    gcp:
      project-id: gosock-bus
google:
  apis:
    sheets:
      credentials-file: ${GOOGLE_CREDENTIALS_FILE_PATH}
      spreadsheet-id: ${GOOGLE_SPREADSHEET_ID}

jwt:
  secret: ${JWT_SECRET_KEY}  # 환경 변수에서 가져옴
  access-token-validity-in-ms: 1800000    # 30분
  refresh-token-validity-in-ms: 604800000  # 7일